# Generated by Django 5.2.6 on 2025-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Untitled Banner', max_length=100),
            preserve_default=False,
        ),
    ]
