# Generated by Django 5.2.6 on 2025-09-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
    ]
